package frc.robot.subsystems;

import static org.wpilib.units.Units.Rotation;
import static org.wpilib.units.Units.Second;
import static org.wpilib.units.Units.Volts;

import java.lang.invoke.ConstantCallSite;
import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANrange;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveDrivetrain.SwerveDriveState;


import choreo.auto.AutoTrajectory;
import choreo.trajectory.SwerveSample;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.util.Nat;
import org.wpilib.util.Pair;
import org.wpilib.math.linalg.VecBuilder;
import org.wpilib.math.controller.ProfiledPIDController;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.geometry.Rotation2d;
import org.wpilib.math.geometry.Transform2d;
import org.wpilib.math.geometry.Translation2d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.math.kinematics.SwerveModuleVelocity;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;
import org.wpilib.math.trajectory.TrapezoidProfile;
import org.wpilib.networktables.DoublePublisher;
import org.wpilib.networktables.NetworkTableInstance;
import org.wpilib.networktables.StructArrayPublisher;
import org.wpilib.driverstation.MatchState;
import org.wpilib.driverstation.RobotState;
import org.wpilib.driverstation.Alliance;
import org.wpilib.driverstation.MatchType;
import org.wpilib.driverstation.DriverStationErrors;
import org.wpilib.driverstation.Alliance;
import org.wpilib.smartdashboard.*;
import org.wpilib.system.Notifier;
import org.wpilib.system.RobotController;
import org.wpilib.command2.Command;
import org.wpilib.command2.Commands;
import org.wpilib.command2.Commands;
import org.wpilib.command2.Subsystem;
import org.wpilib.command2.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import org.wpilib.math.kinematics.SwerveModuleVelocity;
import com.ctre.phoenix6.swerve.SwerveDrivetrain.DeviceConstructor;




/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.ZERO;

    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* PID Control for turning in YAGSL */
    private final ProfiledPIDController thetaController;

    /* Publisher for observed swerve states */
    private final StructArrayPublisher m_observedPublisher = NetworkTableInstance.getDefault().getStructArrayTopic("Swerve/Observed", SwerveModuleVelocity.struct).publish();
    private final DoublePublisher m_thetaControllerPublisher = NetworkTableInstance.getDefault().getDoubleTopic("Swerve/ThetaControllerOut").publish();
    private final DoublePublisher m_trajectoryHeadingPublisher = NetworkTableInstance.getDefault().getDoubleTopic("Swerve/TrajectoryHeading").publish();
    private final DoublePublisher m_trajectoryOmegaPublisher = NetworkTableInstance.getDefault().getDoubleTopic("Swerve/TrajectoryOmega").publish();
    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        TrapezoidProfile.Constraints yagslConstraints = new TrapezoidProfile.Constraints(
            2 * Math.PI,
            2 * Math.PI * Constants.SwerveConstants.kAngularAccelerationFactor);
        thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        TrapezoidProfile.Constraints yagslConstraints = new TrapezoidProfile.Constraints(
            2 * Math.PI,
            2 * Math.PI * Constants.SwerveConstants.kAngularAccelerationFactor);
        thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        TrapezoidProfile.Constraints yagslConstraints = new TrapezoidProfile.Constraints(
            2 * Math.PI,
            2 * Math.PI * Constants.SwerveConstants.kAngularAccelerationFactor);
        thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> {this.setControl(request.get()); m_observedPublisher.set(this.getState().ModuleVelocities);});
    }

    public Command applyOptionalRequest(Supplier<Optional<SwerveRequest>> request) {
        return run (() -> {request.get().ifPresent(req -> this.setControl(req));});
    }

   /* public Command testTurnPID(Supplier<Double> turnAxis) {
        return this.applyRequest(() -> {
        //SmartDashboard.putNumber("Target Angle", turnAxis.get()*Math.PI*2);
        return new SwerveRequest.FieldCentricFacingAngle()
      .withTargetDirection(Rotation2d.fromRadians(turnAxis.get()*Math.PI*2))
      .withHeadingPID(Constants.SwerveConstants.kTurnP, Constants.SwerveConstants.kTurnI, Constants.SwerveConstants.kTurnD)
      .withVelocityX(0)
      .withVelocityY(0);
        });
    }*/

    public void followTrajectory(SwerveSample sample) {
        Pose2d pose = this.getPose();
        m_observedPublisher.set(this.getState().ModuleVelocities); /*ModuleStates was used before, "this.getState().ModuleStates" */
        m_thetaControllerPublisher.set(thetaController.calculate(pose.getRotation().getRadians(), sample.heading));
        m_trajectoryHeadingPublisher.set(sample.heading);
        m_trajectoryOmegaPublisher.set(sample.getTimestamp());
        this.setControl(new SwerveRequest.FieldCentric()
                                .withVelocityX(sample.vx + Constants.ChoreoConstants.xController.calculate(pose.getX(), sample.x))
                                .withVelocityY(sample.vy + Constants.ChoreoConstants.yController.calculate(pose.getY(), sample.y))
                                .withRotationalRate(sample.omega + thetaController.calculate(pose.getRotation().getRadians(), sample.heading)));
    }


    public Pose2d getPose() {
        return this.samplePoseAt(Utils.getCurrentTimeSeconds()).orElse(new Pose2d());
    }

    public Command goToEndPose(AutoTrajectory traj) {
       try {
            Pose2d end = traj.getFinalPose().get();
           return Commands.run(() -> {
               Pose2d pose = this.getPose();
               this.setControl(new SwerveRequest.FieldCentric()
                       .withVelocityX(Constants.ChoreoConstants.xController.calculate(pose.getX(), end.getX()))
                       .withVelocityY(Constants.ChoreoConstants.yController.calculate(pose.getY(), end.getY()))
                       .withRotationalRate(thetaController.calculate(pose.getRotation().getRadians(),
                               end.getRotation().getRadians())));
           }).onlyWhile(() -> (this.getPose().minus(end).getTranslation().getNorm() >= Constants.AutonomousConstants.kStartEndDistanceError && this.getPose().minus(end).getRotation().getRadians() >= Constants.AutonomousConstants.kStartEndRotationError));
       } catch (Exception e) {
        return Commands.none();
       }
    }

    public Command moveToPose(Pose2d targetPose) {
        try {
           return Commands.run(() -> {
               Pose2d pose = this.getPose();
               this.setControl(new SwerveRequest.FieldCentric()
                       .withVelocityX(Constants.ChoreoConstants.xController.calculate(pose.getX(), targetPose.getX()))
                       .withVelocityY(Constants.ChoreoConstants.yController.calculate(pose.getY(), targetPose.getY()))
                       .withRotationalRate(thetaController.calculate(pose.getRotation().getRadians(),
                               targetPose.getRotation().getRadians())));
           }).onlyWhile(() -> (this.getPose().minus(targetPose).getTranslation().getNorm() >= Constants.AutonomousConstants.kStartEndDistanceError && this.getPose().minus(targetPose).getRotation().getRadians() >= Constants.AutonomousConstants.kStartEndRotationError));
       } catch (Exception e) {
        return Commands.none();
       }
    }

    public Command moveToDistanceSensorPoint(CANrange sensor, double xDistance, Pose2d sensorOffset) {
        return run( () -> {
            double xDistanceFromSensor = xDistance - sensorOffset.getX();
            double distanceTriangleBaseAngle = (Math.PI/2) - sensorOffset.getRotation().getRadians();
            double distanceTriangleHypotenuse = sensor.getDistance().getValueAsDouble();

            this.setControl(new SwerveRequest.RobotCentric()
            .withVelocityX(-Constants.ChoreoConstants.xController.calculate(xDistanceFromSensor, Math.cos(distanceTriangleBaseAngle)*distanceTriangleHypotenuse))
            .withVelocityY(0)
            .withRotationalRate(0));

        });
    }

    //Returns robot angle offset and then shooter exit velocity (!!! not rpm). takes in exit velocity in m/s
    public Pair<Double, Double> zippyZoomMath(double desiredExitVelocity, Translation2d targetPoint) {
        Translation2d robotVelocity = new Translation2d(this.getState().Velocity.vx, this.getState().Velocity.vy); 
        Translation2d robotToTarget = targetPoint.minus(this.getPose().getTranslation());
        Translation2d unitInTargetDirection = robotToTarget.div(robotToTarget.getNorm());
        Translation2d unitInOrthDirection = unitInTargetDirection.rotateBy(new Rotation2d(Math.PI/2));

        double robotVelocityTowardsPoint = robotVelocity.dot(unitInTargetDirection);
        double robotVelocityOrthToPoint = robotVelocity.dot(unitInOrthDirection)*Constants.SwerveConstants.kAirResistanceFactor;
        double newExitVelocity = Math.sqrt(Math.pow(desiredExitVelocity - robotVelocityTowardsPoint, 2) + Math.pow(robotVelocityOrthToPoint, 2));
        
        double angleOffset = -Math.asin(robotVelocityOrthToPoint/newExitVelocity);

        return new Pair<Double,Double>(angleOffset, newExitVelocity);
    }

    public Command stopRobot() {
       return Commands.run(() -> {
           this.setControl(new SwerveRequest.FieldCentric().withVelocityX(0).withVelocityY(0).withRotationalRate(0));
       });
   }


   public void resetThetaController() {
    this.thetaController.reset(0, 0);
   }

   public void resetGyro() {
    this.getPigeon2().reset();
   }


    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || RobotState.isDisabled()) {
            MatchState.getAlliance().ifPresent(allianceColor -> {
                setOperatorForwardDirection(kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
  /*   @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
*/
    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
   /*  @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }
*/
    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt((Utils.getCurrentTimeSeconds()-timestampSeconds)*Utils.getMonotonicTimeSeconds());
    }
}

