// spotless:off
package frc.robot.autos;

import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;



/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj AutonomousMoveToElevatorPosition1 = new ChoreoTraj(
        "AutonomousMoveToElevatorPosition1",
        OptionalInt.empty(),
        0.58542,
        new Pose2d(2, 2, Rotation2d.fromRadians(0)),
        new Pose2d(1.6, 3.1, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj DriveToShootPose = new ChoreoTraj(
        "DriveToShootPose",
        OptionalInt.empty(),
        0.78286,
        new Pose2d(3.57341, 4.01511, Rotation2d.fromRadians(0)),
        new Pose2d(2.07341, 4.01511, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj HeadingStdevTuning = new ChoreoTraj(
        "HeadingStdevTuning",
        OptionalInt.empty(),
        8.15069,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(0, 0, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj MovingSpinny = new ChoreoTraj(
        "MovingSpinny",
        OptionalInt.empty(),
        1.0688,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(1, 1, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj NewPath = new ChoreoTraj(
        "NewPath",
        OptionalInt.empty(),
        2.05242,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(1, 0, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Spinny = new ChoreoTraj(
        "Spinny",
        OptionalInt.empty(),
        2.11243,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(0, 0, Rotation2d.fromRadians(3.14159))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("AutonomousMoveToElevatorPosition1", AutonomousMoveToElevatorPosition1),
        Map.entry("DriveToShootPose", DriveToShootPose),
        Map.entry("HeadingStdevTuning", HeadingStdevTuning),
        Map.entry("MovingSpinny", MovingSpinny),
        Map.entry("NewPath", NewPath),
        Map.entry("Spinny", Spinny)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
}
// spotless:on
